Pull request for branch 'logic' that contains functionality for calculator app
jkanyi-web/math-magicians pull request #4
Opened 2023-04-27 15:17 UTC by jkanyi-web

- Added operate.js file that is designed to handle basic arithmetic operations in a calculator application, while also taking into account issues of floating point precision and division by zero.
- Added calculate.js file that handles a variety of cases based on the buttonName, including adding, subtracting, multiplying, and dividing numbers, handling decimal points and negative numbers, and clearing the calculator's memory.
- Added some extra functionality to the calculator input tab to make it display the current value of a calculator's display screen, determined by the state object in calculator.js.
- Declared a useState hook, initialized to an object containing next, total and operation properties.
- Created an event handler function buttonClick that calls the calculate function and updates the state object with the returned result of the calculation

2023-04-27 15:49 UTC, christianbiring1 requested changes
Hi @jkanyi-web , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/234916445-192da391-8e39-4fc9-9843-506d583e7b29.gif)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary` :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] In your README remove the broken link to the live demo or just `Not yet available`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 15:49 UTC, christianbiring1 commented on src/components/Calculator.jsx
> +          *
- [ ] Kindly make sure you use the exact same reference as the ones in `operate.js` as you notice the error in the console while performing the multiplication operation :point_down: 
![image](https://user-images.githubusercontent.com/97100091/234914603-9609366d-c866-4108-aec2-f78f31f09d43.png)

Hint: You may consider saying `x` instead of `*`

2023-04-27 16:22 UTC, AnselemOdims requested changes
### Hi @jkanyi-web , 
Good job implementing some of the changes requested by the previous reviewer.

## Required Changes ♻️
- [ ] Please kindly implement the issue raised by the previous reviewer.

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-27 19:36 UTC, shella12 approved these changes
Hi @jkanyi-web, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Linters are passing ✔️ 
- Implemented all requirements 👏 

## Optional suggestions

- [ ] [OPTIONAL] I see that you used `vite `react app to create this project. I would suggest using `create-react-app` instead. `Create React App` is a popular tool for bootstrapping a new React project and building a web app. It uses `Webpack `and `Babel `under the hood to transpile and bundle your code for the browser. It also includes a development server, a testing framework, and a production build process, among other things. Keep in mind that `Vite` is a simpler and faster build tool, it is designed to handle small-medium size projects, if your project is a large monolithic application, you may want to evaluate if Vite is the best option for you or if you need to stick with `webpack` or other more established build tools.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 06:45 UTC, jkanyi-web commented
Thanks for the positive feedback and the suggestion Shella12. I tried using create-react-app a lot of times to no avail. Every time I used the command, I either got errors saying something has not installed correctly or react installs fully but some key folders and files aren't created, so I just did some research and that's how I landed on Vite.

2023-04-28 06:47 UTC, merged